# Generated by Django 5.0.1 on 2024-01-05 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Legajo',
            fields=[
                ('id_legajo', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=200)),
                ('jerarquia', models.CharField(blank=True, max_length=100, null=True)),
                ('cuerpo', models.CharField(blank=True, max_length=50, null=True)),
                ('fch_leg', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('user_leg', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legajo',
                'verbose_name_plural': 'Legajos',
                'ordering': ['id_legajo'],
            },
        ),
    ]
