# Generated by Django 5.0.1 on 2024-01-15 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistLegajo',
            fields=[
                ('h_id_legajo', models.AutoField(primary_key=True, serialize=False)),
                ('id_legajo', models.PositiveBigIntegerField()),
                ('nro_doc', models.PositiveBigIntegerField()),
                ('nombres', models.CharField(max_length=200)),
                ('jerarquia', models.CharField(blank=True, max_length=100, null=True)),
                ('cuerpo', models.CharField(blank=True, max_length=50, null=True)),
                ('fch_leg', models.DateTimeField(auto_now=True)),
                ('user_leg', models.CharField(max_length=20)),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
                ('h_fch_proc', models.DateTimeField(auto_now_add=True)),
                ('h_tipo_proc', models.CharField(max_length=1, null=True)),
                ('h_user_proc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'H_Legajo',
                'verbose_name_plural': 'H_Legajos',
                'ordering': ['-h_fch_proc'],
            },
        ),
    ]
