# Generated by Django 5.0.1 on 2024-01-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajo', '0002_histlegajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legajo',
            name='id_legajo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
