# Generated by Django 5.0.1 on 2024-01-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajo', '0003_alter_legajo_id_legajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='legajo',
            name='nro_doc',
            field=models.PositiveBigIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
