# Generated by Django 5.0.1 on 2024-01-21 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legajo', '0004_legajo_nro_doc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legajo',
            options={'ordering': ['nro_doc'], 'verbose_name': 'Legajo', 'verbose_name_plural': 'Legajos'},
        ),
    ]
