# Generated by Django 5.0.1 on 2024-01-23 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialadmin',
            options={'verbose_name': 'Historial de Administrador', 'verbose_name_plural': 'Historiales de Administradores'},
        ),
        migrations.AlterModelManagers(
            name='historialadmin',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='historialadmin',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='historialadmin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='historialadmin',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='historialadmin',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='historialadmin',
            name='id',
        ),
        migrations.RemoveField(
            model_name='historialadmin',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historialadmin',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='historialadmin',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='historialadmin',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='historialadmin',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='historialadmin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='historialadmin',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='historialadmin',
            name='user_session',
        ),
        migrations.RemoveField(
            model_name='historialadmin',
            name='username',
        ),
        migrations.AddField(
            model_name='historialadmin',
            name='h_id_admin',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='historialadmin',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
