# Generated by Django 5.0.1 on 2024-01-23 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_alter_historialadmin_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialadmin',
            old_name='user',
            new_name='id_user',
        ),
    ]
