# Generated by Django 5.0.1 on 2024-01-23 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_rename_user_historialadmin_id_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialadmin',
            name='h_id_admin',
        ),
        migrations.RemoveField(
            model_name='historialadmin',
            name='id_user',
        ),
        migrations.AddField(
            model_name='historialadmin',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
