# Generated by Django 5.0.1 on 2024-01-23 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_alter_historialadmin_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialAdmin',
        ),
    ]
