# Generated by Django 5.0.1 on 2024-02-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialadmin',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
