# Generated by Django 5.0.1 on 2024-02-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0008_historialadmin_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialadmin',
            name='h_fch_modificacion',
            field=models.DateTimeField(null=True),
        ),
    ]
