# Generated by Django 5.0.1 on 2024-02-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0009_alter_historialadmin_h_fch_modificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialadmin',
            name='password',
        ),
        migrations.AddField(
            model_name='historialadmin',
            name='h_tipo_proc',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
