# Generated by Django 5.0.1 on 2024-02-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0010_remove_historialadmin_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialadmin',
            name='h_fch_modificacion',
        ),
    ]
