# Generated by Django 4.2.1 on 2023-06-23 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('oficina', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('operador', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, related_name='operador', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fch_operador', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='oficina.oficina')),
                ('user_operador', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='operador_oficina', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
                'ordering': ['operador'],
            },
        ),
    ]
