# Generated by Django 5.0.1 on 2024-01-05 14:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_lote', models.PositiveIntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year_lote', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2023), django.core.validators.MaxValueValidator(2050)])),
                ('Activo_lote', models.BooleanField(default=False)),
                ('importe_lote', models.FloatField(default=0)),
                ('saldo_lote', models.FloatField(default=0)),
                ('fch_lote', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('user_lote', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-year_lote', 'nivel_lote'],
            },
        ),
    ]
