# Generated by Django 5.0.1 on 2024-01-05 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='nivel_lote',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='lote',
            name='year_lote',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2023), django.core.validators.MaxValueValidator(2050)]),
        ),
        migrations.AlterUniqueTogether(
            name='lote',
            unique_together={('nivel_lote', 'year_lote')},
        ),
    ]
