# Generated by Django 5.0.1 on 2024-01-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0002_alter_lote_nivel_lote_alter_lote_year_lote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='Activo_lote',
            field=models.BooleanField(default=True),
        ),
    ]
