# Generated by Django 5.0.1 on 2024-01-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0003_alter_lote_activo_lote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='Activo_lote',
            new_name='activo_lote',
        ),
    ]
