# Generated by Django 5.0.1 on 2024-01-15 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0004_rename_activo_lote_lote_activo_lote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistLote',
            fields=[
                ('h_id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('id_lote', models.PositiveIntegerField()),
                ('nivel_lote', models.PositiveIntegerField()),
                ('year_lote', models.PositiveIntegerField()),
                ('activo_lote', models.BooleanField(default=True)),
                ('importe_lote', models.FloatField(default=0)),
                ('saldo_lote', models.FloatField(default=0)),
                ('fch_lote', models.DateTimeField(auto_now=True)),
                ('user_lote', models.CharField(max_length=20)),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
                ('h_fch_proc', models.DateTimeField(auto_now_add=True)),
                ('h_tipo_proc', models.CharField(max_length=1, null=True)),
                ('h_user_proc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-h_fch_proc'],
            },
        ),
    ]
