# Generated by Django 5.0.1 on 2024-01-15 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0005_histlote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='histlote',
            options={'ordering': ['-h_fch_proc'], 'verbose_name': 'H_Lote', 'verbose_name_plural': 'H_Lotes'},
        ),
    ]
