# Generated by Django 5.0.1 on 2024-01-06 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reclamo', '0001_initial'),
        ('std_mov', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_mov', models.AutoField(primary_key=True, serialize=False)),
                ('fch_std_mov', models.DateField(auto_now_add=True)),
                ('fch_mov', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('id_rec', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reclamo.reclamo')),
                ('id_std_mov', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='std_mov.estadomov')),
                ('user_mov', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientoe',
                'ordering': ['fch_mov'],
            },
        ),
    ]
