# Generated by Django 5.0.1 on 2024-01-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='fch_mov_user',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fch_mov',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fch_std_mov',
            field=models.DateField(),
        ),
    ]
