# Generated by Django 5.0.1 on 2024-01-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0005_movimiento_gde_mov_movimiento_obs_mov'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fch_std_mov'], 'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientoe'},
        ),
    ]
