# Generated by Django 5.0.1 on 2024-01-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0006_alter_movimiento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fch_mov_user',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
