# Generated by Django 5.0.1 on 2024-01-23 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0008_alter_movimiento_options_histmovimiento'),
        ('reclamo', '0005_alter_histreclamo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='id_rec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movs_reclamos', to='reclamo.reclamo'),
        ),
    ]
