# Generated by Django 5.0.1 on 2024-01-08 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_std', models.AutoField(primary_key=True, serialize=False)),
                ('dsc_std', models.CharField(max_length=50, unique=True)),
                ('act_calculo', models.BooleanField(default=True)),
                ('permitido', models.BooleanField(default=True)),
                ('fch_std', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('user_std', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['dsc_std'],
            },
        ),
    ]
