# Generated by Django 5.0.1 on 2024-01-15 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistEstado',
            fields=[
                ('h_id_std', models.AutoField(primary_key=True, serialize=False)),
                ('id_std', models.PositiveBigIntegerField()),
                ('dsc_std', models.CharField(max_length=50, unique=True)),
                ('act_calculo', models.BooleanField(default=True)),
                ('permitido', models.BooleanField(default=True)),
                ('fch_std', models.DateTimeField(auto_now=True)),
                ('user_std', models.CharField(max_length=20)),
                ('slug_std', models.CharField(blank=True, max_length=200, null=True)),
                ('h_fch_proc', models.DateTimeField(auto_now_add=True)),
                ('h_tipo_proc', models.CharField(max_length=1, null=True)),
                ('h_user_proc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'H_Estado',
                'verbose_name_plural': 'H_Estados',
                'ordering': ['-h_fch_proc'],
            },
        ),
    ]
