# Generated by Django 4.2.1 on 2023-06-23 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tipo', '0001_initial'),
        ('clase', '0001_initial'),
        ('marca', '0001_initial'),
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id_bien', models.AutoField(primary_key=True, serialize=False)),
                ('cupi', models.PositiveIntegerField(default=0, unique=True)),
                ('no_inventariado', models.BooleanField(default=False)),
                ('serie', models.CharField(blank=True, default='S/N', max_length=200, null=True)),
                ('nro_inventario', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('qr_bien', models.TextField(blank=True, null=True)),
                ('obs_bien', models.CharField(blank=True, max_length=300, null=True)),
                ('gde_bien', models.CharField(blank=True, max_length=80, null=True)),
                ('fch_bien', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('clase', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='clase', to='clase.clase')),
                ('marca', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='marca', to='marca.marca')),
                ('modelo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='modelo', to='modelo.modelo')),
                ('tipo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tipo', to='tipo.tipo')),
                ('user_bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bien',
                'verbose_name_plural': 'Bienes',
                'ordering': ['tipo'],
            },
        ),
    ]
