# Generated by Django 5.0.1 on 2024-01-06 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reclamo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id_deuda', models.AutoField(primary_key=True, serialize=False)),
                ('neto', models.FloatField(default=0)),
                ('aportes', models.FloatField(default=0)),
                ('contribuciones', models.FloatField(default=0)),
                ('cargas', models.FloatField(default=0)),
                ('interes', models.FloatField(default=0)),
                ('otros', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('fch_calculo', models.DateField()),
                ('fch_deuda', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('id_rec', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reclamo.reclamo', unique=True)),
                ('user_deuda', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deuda',
                'verbose_name_plural': 'Deudas',
                'ordering': ['id_rec'],
            },
        ),
    ]
