# Generated by Django 5.0.1 on 2024-01-15 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deuda', '0002_alter_deuda_id_rec'),
        ('reclamo', '0003_remove_reclamo_activo_rec'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistDeuda',
            fields=[
                ('h_id_deuda', models.AutoField(primary_key=True, serialize=False)),
                ('id_deuda', models.PositiveBigIntegerField()),
                ('neto', models.FloatField(default=0)),
                ('aportes', models.FloatField(default=0)),
                ('contribuciones', models.FloatField(default=0)),
                ('cargas', models.FloatField(default=0)),
                ('interes', models.FloatField(default=0)),
                ('otros', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('fch_calculo', models.DateField()),
                ('fch_deuda', models.DateTimeField(auto_now=True)),
                ('user_deuda', models.CharField(max_length=20)),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
                ('h_fch_proc', models.DateTimeField(auto_now_add=True)),
                ('h_tipo_proc', models.CharField(max_length=1, null=True)),
                ('h_user_proc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('id_rec', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='reclamo.reclamo')),
            ],
            options={
                'verbose_name': 'Deuda',
                'verbose_name_plural': 'Deudas',
                'ordering': ['-h_fch_proc'],
            },
        ),
    ]
