# Generated by Django 5.0.1 on 2024-01-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deuda', '0003_histdeuda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='histdeuda',
            options={'ordering': ['-h_fch_proc'], 'verbose_name': 'H_Deuda', 'verbose_name_plural': 'H_Deudas'},
        ),
    ]
