# Generated by Django 5.0.1 on 2024-01-06 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movimiento', '0001_initial'),
        ('prioridad', '0002_alter_prioridad_dsc_prior_and_more'),
        ('reclamo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rec_Prioridad',
            fields=[
                ('id_rec_prior', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fch_orden', models.DateField(auto_now=True, null=True)),
                ('fch_rec_prior', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('id_mov', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movimiento.movimiento')),
                ('id_prior', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='prioridad.prioridad')),
                ('id_rec', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reclamo.reclamo', unique=True)),
                ('user_rec_prior', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prioridad de Reclamo',
                'verbose_name_plural': 'Prioridad de Reclamos',
                'ordering': ['id_rec'],
            },
        ),
    ]
