# Generated by Django 5.0.1 on 2024-01-11 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_prioridad', '0003_alter_rec_prioridad_id_rec'),
        ('reclamo', '0003_remove_reclamo_activo_rec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec_prioridad',
            name='id_rec',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='reclamo.reclamo'),
        ),
    ]
