# Generated by Django 5.0.1 on 2024-01-12 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec_prioridad', '0004_alter_rec_prioridad_id_rec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rec_prioridad',
            options={'ordering': ['orden'], 'verbose_name': 'Prioridad de Reclamo', 'verbose_name_plural': 'Prioridad de Reclamos'},
        ),
    ]
