# Generated by Django 5.0.1 on 2024-01-13 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_prioridad', '0005_alter_rec_prioridad_options'),
        ('reclamo', '0003_remove_reclamo_activo_rec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec_prioridad',
            name='id_rec',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='prioridad_reclamos', to='reclamo.reclamo'),
        ),
    ]
