# Generated by Django 5.0.1 on 2024-01-15 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0008_alter_movimiento_options_histmovimiento'),
        ('prioridad', '0003_histprioridad'),
        ('rec_prioridad', '0006_alter_rec_prioridad_id_rec'),
        ('reclamo', '0003_remove_reclamo_activo_rec'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistRec_Prioridad',
            fields=[
                ('h_id_rec_prior', models.AutoField(primary_key=True, serialize=False)),
                ('id_rec_prior', models.PositiveIntegerField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fch_orden', models.DateField(auto_now=True, null=True)),
                ('fch_rec_prior', models.DateTimeField(auto_now=True)),
                ('user_rec_prior', models.CharField(max_length=20)),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
                ('h_fch_proc', models.DateTimeField(auto_now_add=True)),
                ('h_tipo_proc', models.CharField(max_length=1, null=True)),
                ('h_user_proc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('id_mov', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movimiento.movimiento')),
                ('id_prior', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='prioridad.prioridad')),
                ('id_rec', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='reclamo.reclamo')),
            ],
            options={
                'verbose_name': 'H_Prioridad de Reclamo',
                'verbose_name_plural': 'H_Prioridad de Reclamos',
                'ordering': ['-h_fch_proc'],
            },
        ),
    ]
