# Generated by Django 5.0.1 on 2024-01-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_prioridad', '0007_histrec_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='histrec_prioridad',
            name='norma_legal_prior',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rec_prioridad',
            name='norma_legal_prior',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
