# Generated by Django 5.0.1 on 2024-01-05 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legajo', '0001_initial'),
        ('tipo_reclamo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id_rec', models.AutoField(primary_key=True, serialize=False)),
                ('fch_dsd_rec', models.DateField()),
                ('fch_hst_rec', models.DateField()),
                ('dias_rec', models.PositiveIntegerField(default=0)),
                ('activo_rec', models.BooleanField(default=False)),
                ('fch_rec', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('id_legajo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='legajos', to='legajo.legajo')),
                ('id_tipo_rec', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tipos_reclamos', to='tipo_reclamo.tiporeclamo')),
                ('user_rec', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reclamo',
                'verbose_name_plural': 'Reclamos',
                'ordering': ['fch_dsd_rec'],
                'unique_together': {('id_legajo', 'fch_dsd_rec', 'fch_hst_rec', 'id_tipo_rec')},
            },
        ),
    ]
