# Generated by Django 5.0.1 on 2024-01-08 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estado', '0001_initial'),
        ('reclamo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='std_rec',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, related_name='estado_reclamos', to='estado.estado'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='activo_rec',
            field=models.BooleanField(default=True),
        ),
    ]
