# Generated by Django 5.0.1 on 2024-01-08 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0002_reclamo_std_rec_alter_reclamo_activo_rec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamo',
            name='activo_rec',
        ),
    ]
