# Generated by Django 5.0.1 on 2024-01-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0004_histreclamo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='histreclamo',
            options={'ordering': ['-h_fch_proc'], 'verbose_name': 'H_Reclamo', 'verbose_name_plural': 'H_Reclamos'},
        ),
    ]
