# Generated by Django 5.0.1 on 2024-01-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0005_alter_histreclamo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='histreclamo',
            name='norma_legal_rec',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='norma_legal_rec',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
