# Generated by Django 5.0.1 on 2024-01-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0006_histreclamo_norma_legal_rec_reclamo_norma_legal_rec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histreclamo',
            name='norma_legal_rec',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
