# Generated by Django 5.0.1 on 2024-01-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0007_alter_histreclamo_norma_legal_rec'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='gde_mov',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
