# Generated by Django 5.0.1 on 2024-01-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0008_reclamo_gde_mov'),
    ]

    operations = [
        migrations.AddField(
            model_name='histreclamo',
            name='gde_mov',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
