# Generated by Django 5.0.1 on 2024-02-05 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0009_histreclamo_gde_mov'),
    ]

    operations = [
        migrations.AddField(
            model_name='histreclamo',
            name='nro_supl',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='histreclamo',
            name='resol_pago_rec',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='histreclamo',
            name='year_cred',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2022), django.core.validators.MaxValueValidator(2050)]),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='nro_supl',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='resol_pago_rec',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='year_cred',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2022), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
