# Generated by Django 5.0.1 on 2024-02-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0010_histreclamo_nro_supl_histreclamo_resol_pago_rec_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='histreclamo',
            old_name='year_cred',
            new_name='year_credito',
        ),
    ]
