# Generated by Django 5.0.1 on 2024-02-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0012_alter_histreclamo_nro_supl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamo',
            old_name='year_cred',
            new_name='year_credito',
        ),
    ]
