# Generated by Django 5.0.1 on 2024-01-15 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_reclamo', '0003_histtiporeclamo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='histtiporeclamo',
            options={'ordering': ['-h_fch_proc'], 'verbose_name': 'H_Tipo Reclamo', 'verbose_name_plural': 'H_Tipos Reclamos'},
        ),
    ]
