# Generated by Django 5.0.1 on 2024-02-05 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_reclamo', '0004_alter_histtiporeclamo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='histtiporeclamo',
            name='codigo_rec',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiporeclamo',
            name='codigo_rec',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
