# Generated by Django 5.0.1 on 2024-01-06 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lote', '0002_alter_lote_nivel_lote_alter_lote_year_lote_and_more'),
        ('reclamo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rec_Lote',
            fields=[
                ('id_lote_rec', models.AutoField(primary_key=True, serialize=False)),
                ('fch_rec_lote', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lote.lote')),
                ('id_rec', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reclamo.reclamo')),
                ('user_rec_lote', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reclamo en lote',
                'verbose_name_plural': 'Reclamos en Lotes',
                'ordering': ['id_rec'],
                'unique_together': {('id_rec', 'id_lote')},
            },
        ),
    ]
