# Generated by Django 5.0.1 on 2024-01-12 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0004_rename_activo_lote_lote_activo_lote'),
        ('rec_lote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec_lote',
            name='id_lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lote.lote'),
        ),
    ]
