# Generated by Django 5.0.1 on 2024-01-13 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_lote', '0002_alter_rec_lote_id_lote'),
        ('reclamo', '0003_remove_reclamo_activo_rec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec_lote',
            name='id_rec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lotes_reclamos', to='reclamo.reclamo'),
        ),
    ]
