# Generated by Django 4.2.1 on 2023-06-23 11:36

import apps.imgbien.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bien', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgBien',
            fields=[
                ('id_img', models.AutoField(primary_key=True, serialize=False)),
                ('img_bien', models.ImageField(null=True, upload_to=apps.imgbien.models.dir_imag)),
                ('fch_bien', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imagenes', to='bien.bien')),
                ('user_bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
