# Generated by Django 5.0.1 on 2024-01-05 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id_prior', models.AutoField(primary_key=True, serialize=False)),
                ('dsc_prior', models.CharField(max_length=50, unique=True)),
                ('nivel_prior', models.PositiveIntegerField(default=0, unique=True)),
                ('fch_prior', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('user_prior', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prioridad',
                'verbose_name_plural': 'Prioridades',
                'ordering': ['nivel_prior'],
            },
        ),
    ]
