# Generated by Django 5.0.1 on 2024-01-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prioridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prioridad',
            name='dsc_prior',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='prioridad',
            name='nivel_prior',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='prioridad',
            unique_together={('dsc_prior', 'nivel_prior')},
        ),
    ]
