# Generated by Django 5.0.1 on 2024-01-15 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prioridad', '0002_alter_prioridad_dsc_prior_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistPrioridad',
            fields=[
                ('h_id_prior', models.AutoField(primary_key=True, serialize=False)),
                ('id_prior', models.IntegerField()),
                ('dsc_prior', models.CharField(max_length=50)),
                ('nivel_prior', models.PositiveIntegerField(default=0)),
                ('fch_prior', models.DateTimeField(auto_now=True)),
                ('user_prior', models.CharField(max_length=20)),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
                ('h_fch_proc', models.DateTimeField(auto_now_add=True)),
                ('h_tipo_proc', models.CharField(max_length=1, null=True)),
                ('h_user_proc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'H_Prioridad',
                'verbose_name_plural': 'H_Prioridades',
                'ordering': ['-h_fch_proc'],
            },
        ),
    ]
