# Generated by Django 5.0.1 on 2024-01-09 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlEstado',
            fields=[
                ('id_contro_std', models.AutoField(primary_key=True, serialize=False)),
                ('fch_control_std', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('std_destino', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='std_destino', to='estado.estado')),
                ('std_origen', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='std_orig', to='estado.estado')),
                ('user_control_std', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control Estado',
                'verbose_name_plural': 'Controles Estados',
                'ordering': ['std_origen'],
            },
        ),
    ]
