# Generated by Django 5.0.1 on 2024-01-15 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_std', '0001_initial'),
        ('estado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistControlEstado',
            fields=[
                ('h_id_contro_std', models.AutoField(primary_key=True, serialize=False)),
                ('id_contro_std', models.IntegerField()),
                ('fch_control_std', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('h_fch_proc', models.DateTimeField(auto_now_add=True)),
                ('h_tipo_proc', models.CharField(max_length=1)),
                ('h_user_proc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('std_destino', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='destino', to='estado.estado')),
                ('std_origen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estado.estado')),
                ('user_control_std', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control Estado',
                'verbose_name_plural': 'Controles Estados',
                'ordering': ['std_origen'],
            },
        ),
    ]
