# Generated by Django 5.0.1 on 2024-01-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_std', '0002_histcontrolestado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='histcontrolestado',
            options={'ordering': ['std_origen'], 'verbose_name': 'H_Control Estado', 'verbose_name_plural': 'H_Controles Estados'},
        ),
        migrations.AlterField(
            model_name='histcontrolestado',
            name='id_contro_std',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='histcontrolestado',
            name='std_destino',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='histcontrolestado',
            name='std_origen',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='histcontrolestado',
            name='user_control_std',
            field=models.CharField(max_length=20),
        ),
    ]
