# Generated by Django 5.0.1 on 2024-01-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_std', '0003_alter_histcontrolestado_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='histcontrolestado',
            old_name='slug',
            new_name='slug_std',
        ),
    ]
