# Generated by Django 5.0.1 on 2024-01-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_std', '0004_rename_slug_histcontrolestado_slug_std'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histcontrolestado',
            name='fch_control_std',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='histcontrolestado',
            name='h_tipo_proc',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='histcontrolestado',
            name='id_contro_std',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='histcontrolestado',
            name='std_destino',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='histcontrolestado',
            name='std_origen',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='histcontrolestado',
            name='user_control_std',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
