# Generated by Django 5.0.1 on 2024-01-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_std', '0005_alter_histcontrolestado_fch_control_std_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='histcontrolestado',
            options={'ordering': ['id_contro_std'], 'verbose_name': 'H_Control Estado', 'verbose_name_plural': 'H_Controles Estados'},
        ),
        migrations.RemoveField(
            model_name='histcontrolestado',
            name='fch_control_std',
        ),
        migrations.RemoveField(
            model_name='histcontrolestado',
            name='h_fch_proc',
        ),
        migrations.RemoveField(
            model_name='histcontrolestado',
            name='h_tipo_proc',
        ),
        migrations.RemoveField(
            model_name='histcontrolestado',
            name='h_user_proc',
        ),
        migrations.RemoveField(
            model_name='histcontrolestado',
            name='slug_std',
        ),
        migrations.RemoveField(
            model_name='histcontrolestado',
            name='std_destino',
        ),
        migrations.RemoveField(
            model_name='histcontrolestado',
            name='std_origen',
        ),
        migrations.RemoveField(
            model_name='histcontrolestado',
            name='user_control_std',
        ),
    ]
