# Generated by Django 5.0.1 on 2024-01-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_std', '0007_histcontrolestado_std_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='histcontrolestado',
            name='std_destino',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
