# Generated by Django 5.0.1 on 2024-01-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_std', '0008_histcontrolestado_std_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='histcontrolestado',
            name='fch_control_std',
            field=models.DateTimeField(null=True),
        ),
    ]
