# Generated by Django 5.0.1 on 2024-01-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_std', '0009_histcontrolestado_fch_control_std'),
    ]

    operations = [
        migrations.AddField(
            model_name='histcontrolestado',
            name='user_control_std',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
