# Generated by Django 5.0.1 on 2024-01-15 12:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_std', '0010_histcontrolestado_user_control_std'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='histcontrolestado',
            name='h_fch_proc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='histcontrolestado',
            name='h_tipo_proc',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='histcontrolestado',
            name='h_user_proc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='histcontrolestado',
            name='slug_std',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
