# Generated by Django 5.0.1 on 2024-01-21 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_std', '0012_alter_histcontrolestado_options'),
        ('estado', '0003_alter_histestado_dsc_std'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlestado',
            name='std_destino',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='std_destino', to='estado.estado'),
        ),
        migrations.AlterField(
            model_name='controlestado',
            name='std_origen',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='std_orig', to='estado.estado'),
        ),
    ]
